import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";

import { compareOutput, parseArgs, renderMarkdown, scanRepository } from "../src/index.js";

test("parseArgs handles path and output options", () => {
  const options = parseArgs(["example", "--out", "AGENTS.md", "--max-files=25", "--no-write", "--check"]);

  assert.equal(options.root, "example");
  assert.equal(options.output, "AGENTS.md");
  assert.equal(options.maxFiles, 25);
  assert.equal(options.write, false);
  assert.equal(options.check, true);
});

test("scanRepository detects package scripts, routes, tests, and hotspots", () => {
  const root = makeTempRepo();

  writeFile(root, "package.json", JSON.stringify({
    packageManager: "pnpm@9.0.0",
    scripts: {
      dev: "next dev",
      test: "vitest",
      build: "next build",
      prepublishOnly: "npm test"
    }
  }, null, 2));
  writeFile(root, "pnpm-lock.yaml", "lockfileVersion: '9.0'\n");
  writeFile(root, "src/index.ts", "export const ok = true;\n");
  writeFile(root, "app/api/health/route.ts", "export function GET() {}\n");
  writeFile(root, "test/index.test.ts", "test('ok', () => {});\n");
  writeFile(root, "src/auth/token.ts", "export const token = '';\n");
  writeFile(root, ".env.example", "API_URL=\n");
  writeFile(root, ".env.local", "SECRET=1\n");
  writeFile(root, ".github/workflows/ci.yml", "name: ci\n");
  writeFile(root, ".npm-cache/cache.js", "const ignored = true;\n");
  writeFile(root, "SECURITY.md", "# Security\n");

  const scan = scanRepository(root);

  assert.equal(scan.packageManager, "pnpm");
  assert.equal(scan.languages.some((item) => item.language === "JavaScript"), false);
  assert.deepEqual(scan.manifests, ["package.json"]);
  assert.ok(scan.commands.some((command) => command.command === "pnpm dev"));
  assert.equal(scan.commands.some((command) => command.command.includes("prepublishOnly")), false);
  assert.ok(scan.routeFiles.includes("app/api/health/route.ts"));
  assert.ok(scan.testFiles.includes("test/index.test.ts"));
  assert.ok(scan.hotspotFiles.includes("src/auth/token.ts"));
  assert.equal(scan.hotspotFiles.includes("SECURITY.md"), false);
  assert.ok(scan.envFiles.includes(".env.example"));
  assert.equal(scan.envFiles.includes(".env.local"), false);
  assert.ok(scan.warnings.some((warning) => warning.includes("Secret-looking `.env` files")));
  assert.ok(scan.ciFiles.includes(".github/workflows/ci.yml"));
});

test("renderMarkdown produces a concise brief", () => {
  const root = makeTempRepo();
  writeFile(root, "package.json", JSON.stringify({ scripts: { test: "node --test" } }, null, 2));
  writeFile(root, "src/index.js", "export {};\n");

  const markdown = renderMarkdown(scanRepository(root));

  assert.match(markdown, /# Agent Brief/);
  assert.match(markdown, /Commands Agents Should Prefer/);
  assert.match(markdown, /npm test/);
  assert.match(markdown, /src\/index\.js/);
});

test("renderMarkdown is deterministic for stale brief checks", () => {
  const root = makeTempRepo();
  writeFile(root, "package.json", JSON.stringify({ scripts: { test: "node --test" } }, null, 2));

  const first = renderMarkdown(scanRepository(root));
  const second = renderMarkdown(scanRepository(root));

  assert.equal(first, second);
  assert.doesNotMatch(first, /Generated by agent-rake .* on /);
});

test("compareOutput detects missing, current, and stale briefs", () => {
  const root = makeTempRepo();
  writeFile(root, "package.json", JSON.stringify({ scripts: { test: "node --test" } }, null, 2));

  const outputPath = path.join(root, "AGENT_BRIEF.md");
  const markdown = renderMarkdown(scanRepository(root));

  assert.deepEqual(compareOutput(markdown, outputPath), { ok: false, reason: "missing" });

  fs.writeFileSync(outputPath, markdown.replace(/\n/g, "\r\n"), "utf8");
  assert.deepEqual(compareOutput(markdown, outputPath), { ok: true, reason: "current" });

  fs.writeFileSync(outputPath, "stale\n", "utf8");
  assert.deepEqual(compareOutput(markdown, outputPath), { ok: false, reason: "stale" });
});

function makeTempRepo() {
  return fs.mkdtempSync(path.join(os.tmpdir(), "agent-rake-"));
}

function writeFile(root, relative, content) {
  const absolute = path.join(root, relative);
  fs.mkdirSync(path.dirname(absolute), { recursive: true });
  fs.writeFileSync(absolute, content, "utf8");
}
