import {
  ALL_TARGETS,
  COMPLETION_SHELLS,
  DEFAULT_MAX_FILES,
  DEFAULT_OUTPUT,
  JAVASCRIPT_LOCK_FILES,
  TARGET_OUTPUTS
} from "./constants.js";

export function renderMarkdown(scan) {
  const lines = [];

  lines.push("# Agent Brief");
  lines.push("");
  lines.push(`Generated by agent-rake for \`${scan.root}\`.`);
  lines.push("");
  lines.push("## Repo Snapshot");
  lines.push("");
  lines.push(`- Root: \`${scan.displayRoot ?? scan.root}\``);
  lines.push(`- Files scanned: ${scan.filesScanned}${scan.truncated ? " (truncated by --max-files)" : ""}`);
  lines.push(`- Primary languages: ${formatLanguageSummary(scan.languages)}`);
  lines.push(`- Package manager: ${scan.packageManager || "not detected"}`);
  if (scan.customIgnores?.length > 0) {
    lines.push(`- Custom ignores: ${scan.customIgnores.map((pattern) => `\`${pattern}\``).join(", ")}`);
  }
  lines.push("");

  lines.push("## Stack Signals");
  lines.push("");
  appendList(lines, "Manifests", scan.manifests);
  appendList(lines, "Lockfiles", scan.lockFiles);
  appendSignals(lines, "Framework signals", scan.frameworks);
  appendSignals(lines, "Workspace signals", scan.workspaces);
  appendList(lines, "Docs", scan.docs);
  appendList(lines, "Existing agent instructions", scan.instructionFiles);
  lines.push("");

  lines.push("## Commands Agents Should Prefer");
  lines.push("");
  if (scan.commands.length === 0) {
    lines.push("- No runnable command was confidently inferred. Read the manifest files before inventing one.");
  } else {
    for (const command of scan.commands) {
      lines.push(`- \`${command.command}\` - ${command.reason}`);
    }
  }
  lines.push("");

  lines.push("## Files To Read First");
  lines.push("");
  appendList(lines, "Entrypoints", scan.entrypoints);
  appendList(lines, "Routes and APIs", scan.routeFiles);
  appendList(lines, "Tests", scan.testFiles);
  appendList(lines, "Environment files", scan.envFiles);
  appendList(lines, "Data and schema files", scan.dataFiles);
  appendList(lines, "CI", scan.ciFiles);
  appendList(lines, "Config", scan.configFiles);
  lines.push("");

  lines.push("## Risk Hotspots");
  lines.push("");
  if (scan.hotspotFiles.length === 0) {
    lines.push("- No obvious auth, payment, migration, webhook, database, queue, or security hotspot files were detected.");
  } else {
    for (const file of scan.hotspotFiles) {
      lines.push(`- \`${file}\``);
    }
  }
  lines.push("");

  lines.push("## Agent Rules For This Repo");
  lines.push("");
  lines.push("- Start with the files listed above before making broad edits.");
  lines.push("- Preserve generated, dependency, cache, build, and vendor directories.");
  lines.push("- Treat `.env` and secret-bearing files as sensitive; prefer examples and docs.");
  lines.push("- Prefer the detected package manager and commands over global fallbacks.");
  lines.push("- Run the smallest relevant test command before claiming a code change is done.");
  lines.push("");

  if (scan.warnings.length > 0) {
    lines.push("## Warnings");
    lines.push("");
    for (const warning of scan.warnings) {
      lines.push(`- ${warning}`);
    }
    lines.push("");
  }

  if (scan.explain) {
    appendExplanations(lines, scan.explanations);
  }

  return `${lines.join("\n").trimEnd()}\n`;
}

export function renderSummary(scan) {
  const warnings = scan.warnings ?? [];
  const lines = [];

  lines.push(`agent-rake summary for \`${scan.displayRoot ?? scan.root}\``);
  lines.push("");
  lines.push(`Status: ${warnings.length > 0 || scan.truncated ? "review warnings" : "no scan warnings"}`);
  lines.push(`Files scanned: ${scan.filesScanned}${scan.truncated ? " (truncated by --max-files)" : ""}`);
  lines.push(`Primary languages: ${formatLanguageSummary(scan.languages)}`);
  lines.push(`Package manager: ${scan.packageManager || "not detected"}`);
  if (scan.customIgnores?.length > 0) {
    lines.push(`Custom ignores: ${formatLimitedList(scan.customIgnores, 6)}`);
  }
  lines.push(`Framework signals: ${formatSignalNames(scan.frameworks)}`);
  lines.push(`Workspace signals: ${formatSignalNames(scan.workspaces)}`);
  lines.push(`Commands: ${formatCommandNames(scan.commands)}`);
  lines.push(`First-read files: ${formatFirstReadCounts(scan)}`);
  lines.push(`Risk hotspots: ${formatHotspotSummary(scan.hotspotFiles)}`);
  lines.push(`Warnings: ${warnings.length === 0 ? "none" : warnings.length}`);

  if (warnings.length > 0) {
    lines.push("");
    lines.push("Warning details:");
    for (const warning of warnings) {
      lines.push(`- ${warning}`);
    }
  }

  return `${lines.join("\n").trimEnd()}\n`;
}

export function renderDoctor(scan, generatedOutput = null) {
  const warnings = scan.warnings ?? [];
  const generatedOutputs = generatedOutput?.outputs ?? [];
  const generatedOutputFailures = generatedOutputs.filter((output) => !output.ok);
  const hasPackageJson = scan.manifests.includes("package.json");
  const hasJsLock = hasJavaScriptLockFile(scan.lockFiles);
  const lines = [];

  lines.push(`agent-rake doctor for \`${scan.displayRoot ?? scan.root}\``);
  lines.push("");
  lines.push(`Status: ${warnings.length === 0 ? "no scan warnings" : `${warnings.length} warning${warnings.length === 1 ? "" : "s"} need review`}`);
  lines.push("");
  lines.push("Checks:");
  appendDoctorCheck(lines, "Scan breadth", !scan.truncated, scan.truncated
    ? "scan hit --max-files before seeing the full repo"
    : `scanned ${scan.filesScanned} files`);
  appendDoctorCheck(lines, "Source files", scan.filesScanned > 0, scan.filesScanned > 0
    ? `${scan.filesScanned} files available for metadata scan`
    : "no source files were found");
  appendDoctorCheck(lines, "Manifest", scan.manifests.length > 0, scan.manifests.length > 0
    ? formatLimitedList(scan.manifests, 4)
    : "no standard project manifest was detected");
  appendDoctorCheck(lines, "JavaScript lockfile", !hasPackageJson || hasJsLock, formatJavaScriptLockDoctorDetail(scan.lockFiles, hasPackageJson, hasJsLock));
  appendDoctorCheck(lines, "Agent instructions", scan.instructionFiles.length > 0, scan.instructionFiles.length > 0
    ? formatLimitedList(scan.instructionFiles, 4)
    : "no AGENTS.md, CLAUDE.md, CODEX.md, Cursor rule, or Copilot instruction file was detected");
  appendDoctorCheck(lines, "Environment hygiene", !warnings.some((warning) => warning.startsWith("Secret-looking `.env` files")), warnings.some((warning) => warning.startsWith("Secret-looking `.env` files"))
    ? "secret-looking .env files were found and intentionally not listed"
    : "no secret-looking .env files detected");
  if (generatedOutputs.length > 0) {
    appendDoctorCheck(lines, "Generated output", generatedOutputs.every((output) => output.ok), formatGeneratedOutputDoctorDetail(generatedOutputs));
  }

  if (warnings.length > 0 || generatedOutputFailures.length > 0) {
    lines.push("");
    lines.push("Fix suggestions:");
    for (const warning of warnings) {
      lines.push(`- ${doctorSuggestionForWarning(warning)}`);
    }
    if (generatedOutputFailures.length > 0) {
      lines.push(`- Run \`${generatedOutput?.updateCommand ?? "agent-rake"}\` to refresh ${formatGeneratedOutputFixTarget(generatedOutputFailures)}.`);
    }
  }

  lines.push("");
  lines.push("Useful next commands:");
  lines.push("- `agent-rake --summary` for a compact snapshot.");
  lines.push("- `agent-rake --diff` before committing generated output.");
  lines.push("- `agent-rake --github-actions` to print a CI workflow.");

  return `${lines.join("\n").trimEnd()}\n`;
}

export function renderTargets() {
  const lines = [];
  const longestName = Math.max(...[...TARGET_OUTPUTS.keys(), ALL_TARGETS].map((name) => name.length));

  lines.push("agent-rake targets");
  lines.push("");
  lines.push("Use with: agent-rake --target <name>");
  lines.push("");

  for (const [name, output] of TARGET_OUTPUTS) {
    lines.push(`${name.padEnd(longestName)}  ${output}`);
  }

  lines.push(`${ALL_TARGETS.padEnd(longestName)}  all known target outputs`);

  return `${lines.join("\n").trimEnd()}\n`;
}

export function renderCompletion(shell) {
  if (!COMPLETION_SHELLS.has(shell)) {
    throw new Error(`--completion must be one of: ${Array.from(COMPLETION_SHELLS).join(", ")}`);
  }

  if (shell === "bash") {
    return renderBashCompletion();
  }

  if (shell === "zsh") {
    return renderZshCompletion();
  }

  if (shell === "fish") {
    return renderFishCompletion();
  }

  return renderPowerShellCompletion();
}

export function renderGitHubActionsWorkflow() {
  return `name: agent-rake

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  agent-rake:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npx agent-rake --diff --strict
`;
}

export function renderConfigExample() {
  return renderRepositoryConfig({
    ignore: [
      "fixtures",
      "src/generated"
    ],
    maxFiles: DEFAULT_MAX_FILES,
    output: DEFAULT_OUTPUT
  });
}

export function renderRepositoryConfig(config) {
  return `${JSON.stringify(config, null, 2)}\n`;
}

export function renderEffectiveConfig(config) {
  return `${JSON.stringify(config, null, 2)}\n`;
}

export function renderOutputDiff(existing, expected, options = {}) {
  const existingLines = splitDiffLines(existing);
  const expectedLines = splitDiffLines(expected);
  const context = options.context ?? 3;
  const maxChangedLines = options.maxChangedLines ?? 80;

  let prefix = 0;
  while (prefix < existingLines.length
    && prefix < expectedLines.length
    && existingLines[prefix] === expectedLines[prefix]) {
    prefix += 1;
  }

  let suffix = 0;
  while (suffix < existingLines.length - prefix
    && suffix < expectedLines.length - prefix
    && existingLines[existingLines.length - 1 - suffix] === expectedLines[expectedLines.length - 1 - suffix]) {
    suffix += 1;
  }

  const oldStart = prefix;
  const oldEnd = existingLines.length - suffix;
  const newEnd = expectedLines.length - suffix;
  const contextStart = Math.max(0, oldStart - context);
  const contextEnd = Math.min(expectedLines.length, newEnd + context);
  const removed = existingLines.slice(oldStart, oldEnd);
  const added = expectedLines.slice(prefix, newEnd);
  const lines = [
    `--- ${options.fromLabel ?? "current"}`,
    `+++ ${options.toLabel ?? "generated"}`,
    `@@ line ${contextStart + 1} @@`
  ];

  for (const line of expectedLines.slice(contextStart, oldStart)) {
    lines.push(`  ${line}`);
  }

  appendChangedDiffLines(lines, "-", removed, maxChangedLines);
  appendChangedDiffLines(lines, "+", added, maxChangedLines);

  if (removed.length > maxChangedLines || added.length > maxChangedLines) {
    lines.push(`  ... diff truncated after ${maxChangedLines} removed and ${maxChangedLines} added lines`);
  }

  for (const line of expectedLines.slice(newEnd, contextEnd)) {
    lines.push(`  ${line}`);
  }

  return `${lines.join("\n").trimEnd()}\n`;
}

function appendList(lines, label, items) {
  if (!items || items.length === 0) {
    lines.push(`- ${label}: none detected`);
    return;
  }

  lines.push(`- ${label}: ${items.map((item) => `\`${item}\``).join(", ")}`);
}

function appendSignals(lines, label, items) {
  if (!items || items.length === 0) {
    lines.push(`- ${label}: none detected`);
    return;
  }

  const formatted = items.map((item) => `\`${item.name}\` (${item.evidence})`);
  lines.push(`- ${label}: ${formatted.join(", ")}`);
}

function formatSignalNames(items) {
  if (!items || items.length === 0) {
    return "none detected";
  }

  return formatLimitedList(items.map((item) => item.name), 6);
}

function renderBashCompletion() {
  const options = [
    "--root",
    "--out",
    "--target",
    "--no-write",
    "--print",
    "--dry-run",
    "--json",
    "--check",
    "--diff",
    "--doctor",
    "--health",
    "--github-actions",
    "--ci-workflow",
    "--install-github-actions",
    "--init-github-actions",
    "--setup",
    "--bootstrap",
    "--summary",
    "--stats",
    "--targets",
    "--list-targets",
    "--explain",
    "--why",
    "--strict",
    "--fail-on-warnings",
    "--force",
    "--config",
    "--no-config",
    "--config-example",
    "--print-config",
    "--init-config",
    "--install-config",
    "--show-config",
    "--effective-config",
    "--completion",
    "--ignore",
    "--max-files",
    "--quiet",
    "--version",
    "--help"
  ].join(" ");
  const targets = [...TARGET_OUTPUTS.keys(), ALL_TARGETS].join(" ");
  const shells = Array.from(COMPLETION_SHELLS).join(" ");

  return `_agent_rake_completion() {
  local cur prev opts targets shells
  COMPREPLY=()
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"
  opts="${options}"
  targets="${targets}"
  shells="${shells}"

  case "$prev" in
    --target)
      COMPREPLY=( $(compgen -W "$targets" -- "$cur") )
      return 0
      ;;
    --completion)
      COMPREPLY=( $(compgen -W "$shells" -- "$cur") )
      return 0
      ;;
    --root|--out|--config|--ignore)
      COMPREPLY=( $(compgen -f -- "$cur") )
      return 0
      ;;
  esac

  COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
}

complete -F _agent_rake_completion agent-rake
`;
}

function renderZshCompletion() {
  const targets = [...TARGET_OUTPUTS.keys(), ALL_TARGETS].join(" ");
  const shells = Array.from(COMPLETION_SHELLS).join(" ");

  return `#compdef agent-rake

_agent_rake() {
  _arguments \\
    '1:repository path:_files -/' \\
    '--root[Repository root]:path:_files -/' \\
    '--out[Output file]:file:_files' \\
    '--target[Known agent output target]:target:(${targets})' \\
    '--no-write[Print Markdown instead of writing]' \\
    '--print[Alias for --no-write]' \\
    '--dry-run[Alias for --no-write]' \\
    '--json[Print scan result as JSON]' \\
    '--check[Fail if output is missing or stale]' \\
    '--diff[Show stale output diff]' \\
    '--doctor[Print health checks and output freshness]' \\
    '--health[Alias for --doctor]' \\
    '--github-actions[Print GitHub Actions workflow]' \\
    '--ci-workflow[Alias for --github-actions]' \\
    '--install-github-actions[Install GitHub Actions workflow safely]' \\
    '--init-github-actions[Alias for --install-github-actions]' \\
    '--setup[Install starter config, workflow, and brief]' \\
    '--bootstrap[Alias for --setup]' \\
    '--summary[Print compact scan summary]' \\
    '--stats[Alias for --summary]' \\
    '--targets[List known target names]' \\
    '--list-targets[Alias for --targets]' \\
    '--explain[Include classification reasons]' \\
    '--why[Alias for --explain]' \\
    '--strict[Exit nonzero on scan warnings or doctor output issues]' \\
    '--fail-on-warnings[Alias for --strict]' \\
    '--force[Overwrite installer targets]' \\
    '--config[Read config file]:file:_files' \\
    '--no-config[Disable config discovery]' \\
    '--config-example[Print example config]' \\
    '--print-config[Alias for --config-example]' \\
    '--init-config[Write config file safely]' \\
    '--install-config[Alias for --init-config]' \\
    '--show-config[Print resolved config]' \\
    '--effective-config[Alias for --show-config]' \\
    '--completion[Print shell completion script]:shell:(${shells})' \\
    '--ignore[Ignore path or segment]:path:_files' \\
    '--max-files[Maximum files to scan]:number:' \\
    '--quiet[Suppress success output when writing]' \\
    '--version[Print version]' \\
    '--help[Print help]'
}

_agent_rake "$@"
`;
}

function renderFishCompletion() {
  const targets = [...TARGET_OUTPUTS.keys(), ALL_TARGETS].join(" ");
  const shells = Array.from(COMPLETION_SHELLS).join(" ");

  return `complete -c agent-rake -f
complete -c agent-rake -l root -r -d 'Repository root'
complete -c agent-rake -l out -r -d 'Output file'
complete -c agent-rake -l target -r -a '${targets}' -d 'Known agent output target'
complete -c agent-rake -l no-write -d 'Print Markdown instead of writing'
complete -c agent-rake -l print -d 'Alias for --no-write'
complete -c agent-rake -l dry-run -d 'Alias for --no-write'
complete -c agent-rake -l json -d 'Print scan result as JSON'
complete -c agent-rake -l check -d 'Fail if output is missing or stale'
complete -c agent-rake -l diff -d 'Show stale output diff'
complete -c agent-rake -l doctor -d 'Print health checks and output freshness'
complete -c agent-rake -l health -d 'Alias for --doctor'
complete -c agent-rake -l github-actions -d 'Print GitHub Actions workflow'
complete -c agent-rake -l ci-workflow -d 'Alias for --github-actions'
complete -c agent-rake -l install-github-actions -d 'Install GitHub Actions workflow safely'
complete -c agent-rake -l init-github-actions -d 'Alias for --install-github-actions'
complete -c agent-rake -l setup -d 'Install starter config, workflow, and brief'
complete -c agent-rake -l bootstrap -d 'Alias for --setup'
complete -c agent-rake -l summary -d 'Print compact scan summary'
complete -c agent-rake -l stats -d 'Alias for --summary'
complete -c agent-rake -l targets -d 'List known target names'
complete -c agent-rake -l list-targets -d 'Alias for --targets'
complete -c agent-rake -l explain -d 'Include classification reasons'
complete -c agent-rake -l why -d 'Alias for --explain'
complete -c agent-rake -l strict -d 'Exit nonzero on scan warnings or doctor output issues'
complete -c agent-rake -l fail-on-warnings -d 'Alias for --strict'
complete -c agent-rake -l force -d 'Overwrite installer targets'
complete -c agent-rake -l config -r -d 'Read config file'
complete -c agent-rake -l no-config -d 'Disable config discovery'
complete -c agent-rake -l config-example -d 'Print example config'
complete -c agent-rake -l print-config -d 'Alias for --config-example'
complete -c agent-rake -l init-config -d 'Write config file safely'
complete -c agent-rake -l install-config -d 'Alias for --init-config'
complete -c agent-rake -l show-config -d 'Print resolved config'
complete -c agent-rake -l effective-config -d 'Alias for --show-config'
complete -c agent-rake -l completion -r -a '${shells}' -d 'Print shell completion script'
complete -c agent-rake -l ignore -r -F -d 'Ignore path or segment'
complete -c agent-rake -l max-files -r -d 'Maximum files to scan'
complete -c agent-rake -l quiet -d 'Suppress success output when writing'
complete -c agent-rake -l version -s v -d 'Print version'
complete -c agent-rake -l help -s h -d 'Print help'
`;
}

function renderPowerShellCompletion() {
  const options = [
    "--root",
    "--out",
    "--target",
    "--no-write",
    "--print",
    "--dry-run",
    "--json",
    "--check",
    "--diff",
    "--doctor",
    "--health",
    "--github-actions",
    "--ci-workflow",
    "--install-github-actions",
    "--init-github-actions",
    "--setup",
    "--bootstrap",
    "--summary",
    "--stats",
    "--targets",
    "--list-targets",
    "--explain",
    "--why",
    "--strict",
    "--fail-on-warnings",
    "--force",
    "--config",
    "--no-config",
    "--config-example",
    "--print-config",
    "--init-config",
    "--install-config",
    "--show-config",
    "--effective-config",
    "--completion",
    "--ignore",
    "--max-files",
    "--quiet",
    "--version",
    "--help"
  ];
  const targets = [...TARGET_OUTPUTS.keys(), ALL_TARGETS];
  const shells = Array.from(COMPLETION_SHELLS);
  const psArray = (values) => values.map((value) => `'${value.replaceAll("'", "''")}'`).join(", ");

  return `Register-ArgumentCompleter -Native -CommandName agent-rake -ScriptBlock {
  param($wordToComplete, $commandAst, $cursorPosition)

  $options = @(${psArray(options)})
  $targets = @(${psArray(targets)})
  $shells = @(${psArray(shells)})
  $tokens = @($commandAst.CommandElements | ForEach-Object { $_.Extent.Text })
  $previous = if ($tokens.Count -ge 2) { $tokens[$tokens.Count - 2] } else { "" }

  if ($previous -eq "--target") {
    $targets |
      Where-Object { $_ -like "$wordToComplete*" } |
      ForEach-Object {
        [System.Management.Automation.CompletionResult]::new($_, $_, [System.Management.Automation.CompletionResultType]::ParameterValue, $_)
      }
    return
  }

  if ($previous -eq "--completion") {
    $shells |
      Where-Object { $_ -like "$wordToComplete*" } |
      ForEach-Object {
        [System.Management.Automation.CompletionResult]::new($_, $_, [System.Management.Automation.CompletionResultType]::ParameterValue, $_)
      }
    return
  }

  if (@("--root", "--out", "--config", "--ignore") -contains $previous) {
    $pathPattern = if ([string]::IsNullOrWhiteSpace($wordToComplete)) { "*" } else { "$wordToComplete*" }

    Get-ChildItem -Path $pathPattern -Force -ErrorAction SilentlyContinue |
      ForEach-Object {
        $completionText = $_.FullName
        if ($_.PSIsContainer) {
          $completionText = $completionText + [System.IO.Path]::DirectorySeparatorChar
        }
        [System.Management.Automation.CompletionResult]::new($completionText, $_.Name, [System.Management.Automation.CompletionResultType]::ProviderItem, $completionText)
      }
    return
  }

  $options |
    Where-Object { $_ -like "$wordToComplete*" } |
    ForEach-Object {
      [System.Management.Automation.CompletionResult]::new($_, $_, [System.Management.Automation.CompletionResultType]::ParameterName, $_)
    }
}
`;
}

function formatCommandNames(commands) {
  if (!commands || commands.length === 0) {
    return "none confidently inferred";
  }

  return formatLimitedList(commands.map((command) => command.command), 6);
}

function formatFirstReadCounts(scan) {
  return [
    `${scan.entrypoints.length} entrypoints`,
    `${scan.routeFiles.length} routes/APIs`,
    `${scan.testFiles.length} tests`,
    `${scan.envFiles.length} env templates`,
    `${scan.dataFiles.length} data/schema`,
    `${scan.ciFiles.length} CI`,
    `${scan.configFiles.length} config`
  ].join(", ");
}

function formatHotspotSummary(files) {
  if (!files || files.length === 0) {
    return "none detected";
  }

  return `${files.length} (${formatLimitedList(files, 3)})`;
}

function appendDoctorCheck(lines, label, ok, detail) {
  lines.push(`- [${ok ? "ok" : "warn"}] ${label}: ${detail}`);
}

function formatJavaScriptLockDoctorDetail(lockFiles, hasPackageJson, hasJsLock) {
  if (!hasPackageJson) {
    return "no package.json manifest detected; check skipped";
  }

  if (hasJsLock) {
    return formatLimitedList(lockFiles.filter((file) => JAVASCRIPT_LOCK_FILES.has(file)), 4);
  }

  return "package.json exists without package-lock.json, pnpm-lock.yaml, yarn.lock, bun.lock, or bun.lockb";
}

function formatGeneratedOutputDoctorDetail(outputs) {
  const staleOutputs = outputs.filter((output) => !output.ok);

  if (staleOutputs.length === 0) {
    return outputs.length === 1
      ? `\`${outputs[0].path}\` is current`
      : `${outputs.length} generated outputs are current`;
  }

  return staleOutputs
    .map((output) => `\`${output.path}\` is ${output.reason}`)
    .join(", ");
}

function formatGeneratedOutputFixTarget(outputs) {
  if (outputs.length === 1) {
    return `\`${outputs[0].path}\``;
  }

  return `${outputs.length} generated outputs`;
}

function doctorSuggestionForWarning(warning) {
  if (warning.startsWith("File scan was truncated")) {
    return "Increase `--max-files`, run from a smaller package root, or add irrelevant large directories to the scanner ignore list.";
  }

  if (warning.startsWith("No source files")) {
    return "Run from the repository root, or add source files before relying on a generated brief.";
  }

  if (warning.startsWith("No standard project manifest")) {
    return "Add or verify a standard manifest such as `package.json`, `pyproject.toml`, `go.mod`, `Cargo.toml`, `composer.json`, `pubspec.yaml`, or `Gemfile`.";
  }

  if (warning.startsWith("package.json exists without")) {
    return "Commit the JavaScript lockfile for the package manager in use, such as `package-lock.json`, `pnpm-lock.yaml`, `yarn.lock`, `bun.lock`, or `bun.lockb`.";
  }

  if (warning.startsWith("No existing AGENTS.md")) {
    return "Create repo instructions with `agent-rake --target agents`, use another single target, or run `agent-rake --target all`.";
  }

  if (warning.startsWith("Secret-looking `.env` files")) {
    return "Keep secret-bearing `.env` files out of generated context and add a safe `.env.example`, `.env.sample`, or `.env.template`.";
  }

  return warning;
}

function formatLimitedList(items, limit) {
  const visible = items.slice(0, limit);
  const suffix = items.length > limit ? `, +${items.length - limit} more` : "";
  return `${visible.map((item) => `\`${item}\``).join(", ")}${suffix}`;
}

function appendExplanations(lines, explanations = []) {
  lines.push("## Why These Signals");
  lines.push("");

  if (explanations.length === 0) {
    lines.push("- No classified signals were available to explain.");
    lines.push("");
    return;
  }

  for (const explanation of explanations) {
    lines.push(`- ${explanation.category} \`${explanation.item}\`: ${explanation.reason}`);
  }

  lines.push("");
}

function formatLanguageSummary(languages) {
  if (!languages || languages.length === 0) {
    return "not detected";
  }

  return languages
    .slice(0, 5)
    .map((item) => `${item.language} (${item.files})`)
    .join(", ");
}

function appendChangedDiffLines(lines, marker, changedLines, maxLines) {
  for (const line of changedLines.slice(0, maxLines)) {
    lines.push(`${marker} ${line}`);
  }
}

function hasJavaScriptLockFile(lockFiles) {
  return lockFiles.some((file) => JAVASCRIPT_LOCK_FILES.has(file));
}

function normalizeLineEndings(value) {
  return value.replace(/\r\n/g, "\n");
}

function splitDiffLines(value) {
  const normalized = normalizeLineEndings(value);
  if (normalized.endsWith("\n")) {
    return normalized.slice(0, -1).split("\n");
  }

  return normalized.split("\n");
}
